version: '2.2'
services:
  # elasticsearch
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: es01
    #环境变量
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #生产环境勿配
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data #数据映射
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml #配置映射
      - ./elastic-stack-ca.p12:/usr/share/elasticsearch/config/elastic-stack-ca.p12 #SSL证书映射
      - ./elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12 #SSL证书映射
    ports:
      - "9200:9200" #端口映射
    networks:
      - elastic #网络
    restart: always #自动重启

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
    networks:
      - elastic
    restart: always

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: es03
    environment:
      - node.name=es03
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
    networks:
      - elastic
    restart: always

  # kibana
  kibana01:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana01
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./elastic-certificates.p12:/usr/share/kibana/config/elastic-certificates.p12
    ports:
      - "5601:5601"
    networks:
      - elastic
    restart: always

  # 心跳检测
  heartbeat01:
    image: docker.elastic.co/beats/heartbeat:7.17.0
    container_name: heartbeat01
    volumes:
      - ./heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
      - ./elastic-certificates.p12:/usr/share/heartbeat/elastic-certificates.p12
    networks:
      - elastic
    restart: always

    # agent 收集 nginx日志
  nginx01:
    image: nginx:1.21.6
    container_name: nginx01
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/access.log:/var/log/nginx/access.log
      - ./nginx/error.log:/var/log/nginx/error.log
    ports:
      - "80:80"
      - "443:443"
    networks:
      - elastic
    restart: always



volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge
